version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
  web:
    build: . 
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      TZ: Asia/Tokyo
    volumes:
      - .:/webapp
    ports:
      - "3000:3000"
    restart: always 
    tty: true 
    stdin_open: true 
    depends_on:
      - db
      - chrome
  chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - 4444:4444
    shm_size: 2gb
volumes:
  postgres_volume:
